blank_issues_enabled: false
contact_links:
  - name: Eclipse Tractus X GitHub organisation Requests
    url: https://eclipse-tractusx.github.io/docs/oss/issues#eclipse-foundation-helpdesk
    about: If you need something for Eclipse Tractus X GitHub organisation we have to raise a GitLab Issue
